### PR TITLE
Kotlin module support

### LINKED ISSUE #6: It doesn't work with @Composable
It give Unresolved reference for composable created in my library

### PR DESCRIPTION
**Pull request by 0xera**
Fixes #6

### CODE REVIEW

File: grease/src/main/kotlin/io/deepmedia/tools/grease/KotlinModuleShadowTransformer.kt [hunk 1]
```diff
@@ -0,0 +1,65 @@
+package io.deepmedia.tools.grease
+
+import com.github.jengelman.gradle.plugins.shadow.transformers.CacheableTransformer
+import com.github.jengelman.gradle.plugins.shadow.transformers.Transformer
+import com.github.jengelman.gradle.plugins.shadow.transformers.TransformerContext
+import org.gradle.api.file.FileTreeElement
+import kotlinx.metadata.jvm.KotlinModuleMetadata
+import kotlinx.metadata.jvm.UnstableMetadataApi
+import org.apache.tools.zip.ZipEntry
+import org.apache.tools.zip.ZipOutputStream
```
Comment (natario1) [inline grease/src/main/kotlin/io/deepmedia/tools/grease/KotlinModuleShadowTransformer.kt:10]: Can't we use Java's ZipOutputStream?

File: grease/src/main/kotlin/io/deepmedia/tools/grease/GreasePlugin.kt [hunk 2]
```diff
@@ -543,14 +521,59 @@ open class GreasePlugin : Plugin<Project> {
...
+            mustRunAfter(bundleLibraryTask)
+        }
+        target.plugins.withId("org.gradle.maven-publish") {
+            target.tasks.withType(PublishToMavenRepository::class.java) {
+                val publication = publication
+                if (publication is DefaultMavenPublication) {
+                    if (creationConfig.name == publication.component.get().name) {
+                        dependsOn(greaseShadowTask)
+                    }
+                }
```
Comment (natario1) [inline grease/src/main/kotlin/io/deepmedia/tools/grease/GreasePlugin.kt:545]: This looks wrong to me. Can you explain what's your goal here? There should be a more a robust solution.

File: grease/src/main/kotlin/io/deepmedia/tools/grease/KotlinModuleShadowTransformer.kt (hunk 1 above)
Comment (0xera) [reply grease/src/main/kotlin/io/deepmedia/tools/grease/KotlinModuleShadowTransformer.kt:10]: This comes from shadow jar dependency, because it is using in transform interface functions

File: grease/src/main/kotlin/io/deepmedia/tools/grease/GreasePlugin.kt (hunk 2 above)
Comment (0xera) [reply grease/src/main/kotlin/io/deepmedia/tools/grease/GreasePlugin.kt:545]: There was problem with publication, because publish task doesnt wait grease tasks, so grease task will be executed after publication and final aar will be incorrect. Therefore i made publish task to execute after grease task for common cases

Comment (natario1) [reply grease/src/main/kotlin/io/deepmedia/tools/grease/GreasePlugin.kt:545]: The main problem is that people should be able to rely on bundle AAR task in all scenarios, without tricks like this one which only solves the publication use-case. We can fix this later though, I'll open an issue with some ideas without using `finalizedBy`.

Another problem is that code above may crash at component.get(). You can do component.getOrNull() but then it may be added later and you don't catch that. 

Maybe it'd be better to iterate over components?

```
project.components.matching { it.name == creationConfig.name }.all {
    tasks.matching { it.name == "generate${creationConfig.name.capitalize()}PomFileForPublication" }.configureEach {
        mustRunAfter(greaseShadowTask)
    }
}
```

Comment (0xera) [reply grease/src/main/kotlin/io/deepmedia/tools/grease/GreasePlugin.kt:545]: Maybe, but there is so many publish tasks and we can skip one of them. Also we are configuring grease after evaluation so i think everything should be good

**Review by natario1 — APPROVED** [review]
